spring:
  application:
    name: order-service
  config:
    import: "optional:configserver:http://config-server:8088"
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
