server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/product/**
          filters:
            - RewritePath=/api/v1/product/(?<remaining>.*), /api/v1/${remaining}
        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/api/v1/cart/**
          filters:
            - RewritePath=/api/v1/cart/(?<remaining>.*), /api/v1/${remaining}
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order/**
          filters:
            - RewritePath=/api/v1/order/(?<remaining>.*), /api/v1/${remaining}