server:
  port: 8083

spring:
  session:
    redis:
      serializer: json

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    hostname: cart-service

resilience4j:
  retry:
    instances:
      productService:
        max-attempts: 3
        wait-duration: 500ms
  circuitbreaker:
    instances:
      productService:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10