server:
  port: 8083

spring:
  session:
    redis:
      serializer: json

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    hostname: cart-service