server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    hostname: order-service

resilience4j:
  retry:
    instances:
      cartService:
        max-attempts: 3
        wait-duration: 2s
  circuitbreaker:
    instances:
      cartService:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-size: 5