server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    hostname: order-service

resilience4j:
  retry:
    instances:
      cartService:
        max-attempts: 3
        wait-duration: 2s