server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    hostname: product-service

spring:
  jackson:
    default-property-inclusion: non_null